version: '3'

services:
  nginx:
    image: nginx:1.15.5
    container_name: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 3000:80
    depends_on:
      - ipfs
    networks:
      - proxy-tier
  ipfs:
    image: ipfs/go-ipfs:v0.4.18
    container_name: ipfs
    ports:
      - 4001:4001
      - 5001:5001
      - 8080:8080
    networks:
      - proxy-tier
    environment:
      - IPFS_LOGGING=error

networks:
  proxy-tier:
